CREATE DATABASE DE_06
IF OBJECT_ID('KHACHHANG') IS NOT NULL
DROP TABLE KHACHHANG
GO
CREATE TABLE KHACHHANG
(
	MA_KH VARCHAR(10) NOT NULL,
	HO_TEN NVARCHAR(50) NULL,
	NGAY_SINH DATETIME NULL,
	QUE_QUAN NVARCHAR(50) NULL,
	GTINH NVARCHAR(10) NULL,
	CONSTRAINT PK_KHACHHANG PRIMARY KEY(MA_KH)
)
IF OBJECT_ID('NHANVIEN') IS NOT NULL
DROP TABLE NHANVIEN
GO
CREATE TABLE NHANVIEN
(
	MA_NV VARCHAR(10) NOT NULL,
	HOTEN_NV NVARCHAR(50) NULL,
	NAM_LV INT NULL,
	LUONG MONEY NULL,
	CONSTRAINT PK_NHANVIEN PRIMARY KEY(MA_NV)
)
IF OBJECT_ID('DONDATHANG') IS NOT NULL
DROP TABLE DONDATHANG
GO
CREATE TABLE DONDATHANG
(
	 MA_HD VARCHAR(10) NOT NULL,
	 MA_KH VARCHAR(10) NOT NULL,
	 MA_NV VARCHAR(10) NOT NULL,
	 SAN_PHAM NVARCHAR(50) NULL,
	 CONSTRAINT PK_DONDATHANG PRIMARY KEY(MA_HD),
	 CONSTRAINT FK_KHACHHANG_DONDATHANG FOREIGN KEY(MA_KH) REFERENCES KHACHHANG,
	 CONSTRAINT FK_NHANVIEN_DONDATHANG FOREIGN KEY(MA_NV) REFERENCES NHANVIEN
)
----NHẬP DỮ LIỆU
DELETE FROM KHACHHANG
INSERT INTO KHACHHANG 
VALUES   ('KH01',N'TRẦN THỊ HOA','4/5/1977',N'HÀ NỘI',N'NỮ'),
		 ('KH02',N'NGUYỄN PHONG','5/3/1999',N'HÀ NỘI',N'NAM'),
		 ('KH03',N'ĐẶNG BẢO NAM','5/1/1991',N'NAM ĐỊNH',N'NAM')
DELETE FROM NHANVIEN
INSERT INTO NHANVIEN
VALUES 	('NV1',N'TRẦN AN NHIÊN',2013,60000000),
		('NV2',N'LÊ BÌNH AN',2018,90000000),
		('NV3',N'PHAN HUY VĂN',2019,50000000)
DELETE FROM DONDATHANG
INSERT INTO DONDATHANG
VALUES 	('H001','KH01','NV1',N'BÁNH GẠO'),
		('H002','KH02','NV1',N'GIÀY'),
		('H003','KH03','NV2',N'TÚI')
SELECT * FROM KHACHHANG
SELECT * FROM NHANVIEN
SELECT * FROM DONDATHANG

/*Câu 2: Đưa ra thông tin: mã khách hàng, họ tên,  giới tính của những 
khách hàng đặt sản phẩm giày. (1đ)*/
SELECT KHACHHANG.MA_KH,HO_TEN,GTINH
FROM KHACHHANG JOIN DONDATHANG ON DONDATHANG.MA_KH=KHACHHANG.MA_KH
WHERE SAN_PHAM = N'GIÀY'
/*Câu 3: Đưa ra thông tin: Makh, Hoten, Tuoi của những khách hàng 
có tuổi>18 và Quequan là ‘Hà Nội’ (1đ)*/
SELECT MA_KH,HO_TEN,DATEDIFF(YEAR,NGAY_SINH,GETDATE()) AS TUOI
FROM KHACHHANG 
WHERE DATEDIFF(YEAR,NGAY_SINH,GETDATE()) > 18 AND QUE_QUAN = N'HÀ NỘI'
/*Câu 4: Đưa ra thông tin nhân viên bán được ít sản phẩm nhất 
Thông tin hiển thị gồm có: Manv, HotenNV, số lượng sản phẩm (1đ)*/
SELECT TOP 1 NHANVIEN.MA_NV,HOTEN_NV,COUNT(MA_HD) AS SO_LUONG
FROM NHANVIEN JOIN DONDATHANG ON DONDATHANG.MA_NV=NHANVIEN.MA_NV
GROUP BY NHANVIEN.MA_NV,HOTEN_NV
ORDER BY COUNT(MA_HD) ASC
/*Câu 5: Đưa ra danh sách :manv, hotenNV của những nhân viên có
lương trên mức lương trung bình của nhân viên. (1đ)*/
SELECT MA_NV,HOTEN_NV,LUONG 
FROM NHANVIEN 
GROUP BY MA_NV,HOTEN_NV,LUONG HAVING LUONG > AVG(LUONG) 
/*Câu 6: Thêm một bản ghi mới vào bảng NHÂNVIEEN,dữ liệu phù hợp
( không được nhập giá trị null). (1đ)*/
INSERT INTO NHANVIEN VALUES 	('NV4',N'TRẦN AN KHANG',2016,70000000)
/*Câu 7: Thay đổi năm làm việc của nhân viên Có
An trong tên thành 2010. (1đ)*/
UPDATE NHANVIEN SET NAM_LV = 2010
WHERE HOTEN_NV LIKE N'%AN'
SELECT * FROM NHANVIEN
/*Câu 8: Xóa nhân viên ăn hại (không bán được hàng). */
DELETE FROM NHANVIEN WHERE NOT EXISTS (SELECT MA_NV FROM DONDATHANG 
								WHERE DONDATHANG.MA_NV=NHANVIEN.MA_NV)