------TẠO DATABASE
CREATE DATABASE LAB6
-----TẠO BẢNG
-----BẢNG PHONGBAN
IF OBJECT_ID('PHONGBAN') IS NOT NULL
DROP TABLE PHONGBAN
GO
CREATE TABLE PHONGBAN
(
	MAPB VARCHAR(10) NOT NULL,
	TENPB NVARCHAR(30),
	NGANSACH MONEY,
	CONSTRAINT PK_PHONGBAN PRIMARY KEY(MAPB)
)
----Bảng CONGVIEC
IF OBJECT_ID('CONGVIEC') IS NOT NULL
DROP TABLE CONGVIEC
GO
CREATE TABLE CONGVIEC
(
	MACV VARCHAR(10) NOT NULL,
	TENCV NVARCHAR(30),
	LUONGMIN MONEY,
	LUONGMAX MONEY,
	CONSTRAINT PK_CONGVIEC PRIMARY KEY(MACV)
)
----BẢNG NHANVIEN
IF OBJECT_ID('NHANVIEN') IS NOT NULL
DROP TABLE NHANVIEN
GO
CREATE TABLE NHANVIEN
(
	MANV VARCHAR(10) NOT NULL,
	HOTENNV NVARCHAR(30),
	LCB MONEY,
	NGSINH DATETIME,
	GTINH NVARCHAR(10),
	MACV VARCHAR(10) NOT NULL,
	MAPB VARCHAR(10) NOT NULL,
	CONSTRAINT PK_NHANVIEN PRIMARY KEY(MANV),
	CONSTRAINT FK_NHANVIEN_PHONGBAN FOREIGN KEY(MAPB) REFERENCES PHONGBAN,
	CONSTRAINT FK_NHANVIEN_CONGVIEC FOREIGN KEY(MACV) REFERENCES CONGVIEC
)
----NHẬP DỮ LIỆU
-------BẢNG PHÒNG BAN
DELETE FROM PHONGBAN
INSERT INTO PHONGBAN VALUES
        ('HC',N'HÀNH CHÍNH',5000000),
        ('KT',N'KỸ THUẬT',7000000),
        ('KD',N'KINH DOANH',10000000)
-------BẢNG CÔNG VIỆC
DELETE FROM CONGVIEC
INSERT INTO CONGVIEC VALUES
        ('CV01',N'SỬA CHỮA ĐIỆN NƯỚC',200000,800000),
        ('CV02',N'DỌN DẸP',100000,500000),
        ('CV03',N'BÁN SẢN PHẨM',800000,2200000)
-------BẢNG NHÂN VIÊN
DELETE FROM NHANVIEN
INSERT INTO NHANVIEN VALUES
        ('NV01',N'TRẦN HOÀNG ANH',5000000,'08-08-1977',N'NAM','CV02','KT'),
        ('NV02',N'NGUYỄN TRÀ MY',4000000,'10-20-1982',N'NỮ','CV02','HC'),
        ('NV03',N'LÊ TUẤN TÚ',6000000,'10-11-1991',N'NAM','CV01','KD')
SELECT * FROM PHONGBAN
SELECT * FROM CONGVIEC
SELECT * FROM NHANVIEN
---TRUY VẤN
/*Câu 2: Thực hiện các truy vấn sau:
a. Hiển thị các nhân viên mà có tuổi từ 40 trở lên bao gồm các thông tin sau: MANV, HOTEN, TENCV, LUONG, NGAYSINH,
TUỔI. (1 điểm)*/
SELECT MANV,HOTENNV,TENCV,LCB,NGSINH,DATEDIFF(YEAR,NGSINH,GETDATE()) AS TUOI
FROM NHANVIEN JOIN CONGVIEC ON CONGVIEC.MACV=NHANVIEN.MACV
WHERE DATEDIFF(YEAR,NGSINH,GETDATE()) > 40
/*b. Hiển thị các nhân viên có LUONG_MIN từ 950000 đến 1300000 bao gồm các thông tin: MANV, HOTENNV, TENCV,
TENPB, LUONG_MIN. (1 điểm)*/
SELECT MANV,HOTENNV,TENCV,TENPB,LUONGMIN
FROM NHANVIEN JOIN CONGVIEC ON CONGVIEC.MACV=NHANVIEN.MACV
			  JOIN PHONGBAN ON PHONGBAN.MAPB=NHANVIEN.MAPB
WHERE LUONGMIN BETWEEN 200000 AND 800000
/*c. Hiển thị các thông tin NHANVIEN  họ nguyễn bao gồm các thông tin: MNV, TENNV, TENPB, TENCV. (1 điểm)*/
SELECT MANV,HOTENNV,TENPB,TENCV 
FROM NHANVIEN  JOIN CONGVIEC ON CONGVIEC.MACV=NHANVIEN.MACV
			  JOIN PHONGBAN ON PHONGBAN.MAPB=NHANVIEN.MAPB
WHERE HOTENNV LIKE N'NGUYỄN%'
/*d. Liệt kê các nhân viên có LCB cao nhất gồm các thông tin: MANV, HOTENNV, LCB, TENPB. (1 điểm)*/
SELECT MANV,HOTENNV,LCB,TENPB 
FROM NHANVIEN  JOIN CONGVIEC ON CONGVIEC.MACV=NHANVIEN.MACV
			  JOIN PHONGBAN ON PHONGBAN.MAPB=NHANVIEN.MAPB
ORDER BY LCB DESC
/*e. Hiển thị thông tin của những phòng ban không có nhân viên nào gồm: MAPB, TENPB. (1 điểm).*/
SELECT MAPB,TENPB FROM PHONGBAN
WHERE NOT EXISTS (SELECT MAPB,TENPB FROM NHANVIEN WHERE NHANVIEN.MAPB=PHONGBAN.MAPB)
/*f. Chèn thêm thông tin vào bảng NHANVIEN (Dữ liệu các cột không được để trống) (1 điểm).*/ /*CHẠY KHÔNG ĐƯỢC*/
INSERT INTO NHANVIEN VALUES ('NV04',N'LÊ ANH KHOA',9000000,'11-11-1993',N'NAM','CV01','HC')
/*g.  Xóa toàn bộ thông tin MACV là CV02. (1 điểm).*/
-----XÓA KHÓA NGOẠI TRƯỚC
DELETE FROM NHANVIEN WHERE MACV = 'CV02'

DELETE FROM CONGVIEC WHERE MACV = 'CV02'

	

			
