CREATE DATABASE QLNV

CREATE TABLE PHONGBAN
(
	MAPB     NVARCHAR(10) NOT NULL,
   TENPB      NVARCHAR(20) NULL,
   NGANSACH    MONEY    NULL,
  CONSTRAINT  PK_PHONGBAN PRIMARY KEY(MAPB)
)

CREATE TABLE CONGVIEC
(
	MACV NVARCHAR(10) NOT NULL,
	TENCV NVARCHAR(20) NULL,
	LUONG_MIN   MONEY    NULL,
	LUONG_MAX   MONEY    NULL
	CONSTRAINT  PK_CONGVIEC PRIMARY KEY(MACV)
)

CREATE TABLE NHANVIEN
(
	MANV NVARCHAR(10) NOT NULL,
	HOTENNV NVARCHAR(50) NOT NULL,
	LCB    MONEY    NULL,
	NGAYSINH   DATETIME    NULL,
	GT NVARCHAR(10) NULL,
	MACV  NVARCHAR(10) NOT NULL,
	MAPB  NVARCHAR(10) NOT NULL,
	CONSTRAINT FK_NHANVIEN_PHONGBAN FOREIGN KEY (MAPB)
			REFERENCES PHONGBAN,
	CONSTRAINT FK_NHANVIEN_CONGVIEC FOREIGN KEY (MACV)
			REFERENCES CONGVIEC,
	CONSTRAINT PK_NHANVIEN PRIMARY KEY (MAPB,MACV)
)


