---tạo database
CREATE DATABASE QLBDS_LAB5
---BANG VANPHONG
IF OBJECT_ID('VANPHONG') IS NOT NULL
 DROP TABLE VANPHONG
 GO
 CREATE TABLE VANPHONG
 (
	MA_VP VARCHAR(10) NOT NULL,
	TEN_VP NVARCHAR(50) NULL,
	SDT   NVARCHAR(15) NULL,
	EMAIL NVARCHAR(50) NULL,
	TRUONGPHONG NVARCHAR(50) NULL,
	CONSTRAINT PK_VANPHONG PRIMARY KEY(MA_VP)
)
-------BANG BDS
CREATE DATABASE BDS
IF OBJECT_ID('BDS') IS NOT NULL
	DROP TABLE BDS
GO
CREATE TABLE BDS
(
	MA_BDS VARCHAR(10) NOT NULL,
	TEN_BDS NVARCHAR(50) NULL,
	DIACHI NVARCHAR(50) NULL,
	MA_CSH NVARCHAR(10) NULL,
	MA_VP VARCHAR(10) NOT NULL,
	CONSTRAINT PK_BDS PRIMARY KEY(MA_BDS),
	CONSTRAINT FK_BDS_VANPHONG FOREIGN KEY(MA_VP)
				REFERENCES VANPHONG 
)
-----NHAP DU LIEU
---BANG VANPHONG
DELETE FROM VANPHONG
INSERT INTO VANPHONG VALUES /*mavp,tenvp,sdt,email,truongphong*/
	('VP01',N'HÀ NỘI','0977584676','HNBDS@FPT.EDU.VN','TP01'),
	('VP02',N'ĐÀ NẴNG','0879654321','DNBDS@FPT.EDU.VN','TP02'),
	('VP03',N'NHA TRANG','0912345678','NTBDS@FPT.EDU.VN','TP03')
--------BANG BDS
DELETE FROM BDS
INSERT INTO BDS VALUES -----MABDS,TENBDS,DIACHI,MACSH,MAVP
	('DT01',N'CHƯNG CƯ',N'SỐ 1 TRỊNH VĂN BÔ NAM TỪ LIÊM HÀ NỘI','001','VP01'),
	('DT02',N'NHÀ VƯỜN',N'15 LIÊN CHIỂU ĐÀ NẴNG','002','VP01'),
	('DT03',N'BIỆT THỰ',N'113 TRẦN HƯNG ĐẠO QUẬN 1 TP HCM','003','VP03')

----TRUY VẤN
SELECT * FROM VANPHONG
SELECT * FROM BDS

--------BÀI 2: TRUY VẤN
/*1. Hiển thị thông tin Văn phòng bao gồm: MAVP, TENVP.*/
SELECT MA_VP,TEN_VP FROM VANPHONG
/*2: Hiển thị thông tin BDS gồm: MABDS, MAVP, Tenbds, diachi. Trong đó: Chỉ hiển thị
những địa chỉ ở Hà Nội.*/
SELECT MA_BDS,MA_VP,TEN_BDS,DIACHI FROM BDS
WHERE DIACHI LIKE N'%HÀ NỘI'
/*3. Hiển thị tất cả BDS có mã văn phòng kết thúc là ‘01’.*/
SELECT*FROM BDS WHERE MA_VP LIKE '%01'
/*4. Hiển thị tất cả thông tin trong bảng VANPHONG của những văn phòng có tenvp bắt đầu là chữ ‘N’.*/
SELECT * FROM VANPHONG 
WHERE TEN_VP LIKE N'N%'
/*5. Hiển thị MAVP và số LƯỢNG văn phòng. Yêu cầu chỉ hiển thị mavp nào có số văn phòng >=1.Sắp xếp MAVPtheo thứ tự tăng dần.*/
SELECT MA_VP,COUNT(MA_VP) AS SOVP
FROM BDS 
GROUP BY MA_VP
HAVING COUNT(MA_VP)>=1         ----KHÔNG HIỂU
ORDER BY MA_VP ASC
/*6. Đưa ra văn phòng bán được nhiều BDS nhất gồm: mavp, soluong:*/
SELECT TOP 1 MA_VP, COUNT(MA_VP) AS SL
FROM BDS
GROUP BY MA_VP
ORDER BY SL DESC