CREATE DATABASE QLDH
IF OBJECT_ID('KHACHHANG') IS NOT NULL
DROP TABLE KHACHHANG
GO
CREATE TABLE KHACHHANG
(
	MA_KH VARCHAR(10) NOT NULL,
	TEN_KH NVARCHAR(50) NULL,
	TAIKHOAN NVARCHAR(50) NULL,
	CONSTRAINT PK_KHACHHANG PRIMARY KEY(MA_KH)
)
IF OBJECT_ID('SACH') IS NOT NULL
DROP TABLE SACH
GO
CREATE TABLE SACH
(
	MA_SACH VARCHAR(10) NOT NULL,
	TIEU_DE NVARCHAR(50) NULL,
	DON_GIA MONEY NULL,
	GHI_CHU NVARCHAR(50) NULL,
	CONSTRAINT PK_SACH PRIMARY KEY(MA_SACH),
	
)
IF OBJECT_ID('DONHANG') IS NOT NULL
DROP TABLE DONHANG
GO
CREATE TABLE DONHANG
(
	MA_DH VARCHAR(10) NOT NULL,
	MA_KH VARCHAR(10) NOT NULL,
	MA_SACH VARCHAR(10) NOT NULL,
	SO_LUONG INT NULL,
	CONSTRAINT PK_DONHANG PRIMARY KEY(MA_DH),
	CONSTRAINT FK_SACH_DONHANG FOREIGN KEY(MA_SACH) REFERENCES SACH,
	CONSTRAINT FK_KHACHHANG_DONHANG FOREIGN KEY(MA_KH) REFERENCES KHACHHANG
)
-------NHẬP DỮ LIỆU
DELETE FROM KHACHHANG
INSERT INTO KHACHHANG 
VALUES  ('KH1',N'TÙNG','00054502'),
		('KH2',N'NGA','00082347'),
		('KH3',N'VÂN','00056341')
DELETE FROM SACH
INSERT INTO SACH 
VALUES ('S01',N'TIN HỌC',75000,N'MỚI NHẬP'),
		('S02',N'VĂN HỌC',82000,N'HẾT SÁCH'),
		('S03',N'CÔNG NGHỆ',110000,N'CÒN SÁCH')
DELETE FROM DONHANG
INSERT INTO DONHANG 
VALUES ( '001','KH1','S02',7),
		( '002','KH1','S03',10),
		( '003','KH3','S02',20)
SELECT * FROM KHACHHANG
SELECT * FROM SACH
SELECT * FROM DONHANG

/*Câu 2: Hiển thị thông tin: MaKH, TenKH, Masach, soluong, dongia, thanhtien */
SELECT KHACHHANG.MA_KH,TEN_KH,SACH.MA_SACH,SO_LUONG,DON_GIA, SO_LUONG * DON_GIA AS THANHTIEN
FROM KHACHHANG JOIN DONHANG ON DONHANG.MA_KH=KHACHHANG.MA_KH
				JOIN SACH ON SACH.MA_SACH=DONHANG.MA_SACH
/*Câu 3: Hiển thị Top 2 khách hàng mua hàng với số tiền nhiều nhất
gồm các thông tin sau: MaKH, Masach, soluong, dongia, thanhtien (1 điểm)*/
SELECT TOP 2 KHACHHANG.MA_KH,SACH.MA_SACH,SO_LUONG,DON_GIA, SUM(SO_LUONG * DON_GIA) AS THANHTIEN
FROM KHACHHANG JOIN DONHANG ON DONHANG.MA_KH=KHACHHANG.MA_KH
				JOIN SACH ON SACH.MA_SACH=DONHANG.MA_SACH
GROUP BY KHACHHANG.MA_KH,SACH.MA_SACH,SO_LUONG,DON_GIA
ORDER BY SUM(SO_LUONG * DON_GIA) DESC
/*Câu 4: Hiển thị các sách có số lượng nằm trong khoảng từ 10 đến 20. (1 điểm)*/
SELECT TIEU_DE,SACH.MA_SACH,SO_LUONG
FROM SACH JOIN DONHANG ON DONHANG.MA_SACH=SACH.MA_SACH
WHERE SO_LUONG BETWEEN 10 AND 20
/*Câu 5: Hiển thị MaDH, MaKH, tổng thành tiền đã mua trong từng đơn hàng. Chỉ
hiển thị những đơn hàng có tổng thành tiền >=500.000 và sắp xếp theo 
thứ tự giảm dần của cột tổng thành tiền. (1 điểm)*/
SELECT MA_DH,KHACHHANG.MA_KH,SUM(SO_LUONG * DON_GIA) AS TONGTHANHTIEN
FROM DONHANG JOIN KHACHHANG ON KHACHHANG.MA_KH=DONHANG.MA_KH
			 JOIN SACH ON SACH.MA_SACH=DONHANG.MA_SACH
GROUP BY MA_DH,KHACHHANG.MA_KH
HAVING SUM(SO_LUONG * DON_GIA)  >= 500.000
ORDER BY SUM(SO_LUONG * DON_GIA) DESC
/*Câu 6: Hiển thị tên sách có số lượng  đặt mua nhỏ hơn số lượng mua trung bình của các sách. (1 điểm)*/
SELECT TIEU_DE
FROM SACH  JOIN DONHANG ON  DONHANG.MA_SACH = SACH.MA_SACH
GROUP BY TIEU_DE 
HAVING SUM(SO_LUONG) < (SELECT SUM(SO_LUONG) FROM DONHANG)/(SELECT COUNT(MA_SACH) FROM SACH)
/*Câu 7: Chèn thêm một bản ghi mới vào bảng SACH.  (1 điểm)*/
INSERT INTO SACH VALUES ('S04',N'VĂN HỌC',72000,N'HẾT SÁCH')
/*Câu 8: Cập nhật lại số TAIKHOAN của khách hàng  KH3 là: “00000001” */
UPDATE KHACHHANG SET TAIKHOAN = '00000001'
WHERE MA_KH = 'KH3'