-------TẠO CSDL
CREATE DATABASE DE_5
---BẢNG PHONGBAN
IF OBJECT_ID('PHONGBAN') IS NOT NULL
 DROP TABLE PHONGBAN
 GO
 CREATE TABLE PHONGBAN
 (
	MA_PB VARCHAR(10) NOT NULL,
	TEN_PB NVARCHAR(50) NULL,
	NGANSACH MONEY NULL,
	CONSTRAINT PK_PHONGBAN PRIMARY KEY (MA_PB)
 )
 ---BẢNG CONGVIEC
IF OBJECT_ID('CONGVIEC') IS NOT NULL
 DROP TABLE CONGVIEC
 GO
 CREATE TABLE CONGVIEC
 (
	MA_CV VARCHAR(10) NOT NULL,
	TEN_CV NVARCHAR(50) NULL,
	LUONG_MIN MONEY  NULL,
	LUONG_MAX MONEY NULL,
	CONSTRAINT PK_CONGVIEC PRIMARY KEY(MA_CV)
)
 ---BẢNG NHANVIEN
IF OBJECT_ID('NHANVIEN') IS NOT NULL
 DROP TABLE NHANVIEN
 GO
 CREATE TABLE NHANVIEN
 (
	MA_NV VARCHAR(10) NOT NULL,
	HOTEN_NV NVARCHAR(50) NULL,
	LCB MONEY  NULL,
	NGAYSINH DATE  NULL,
	GT    NVARCHAR (10) NULL,
	MA_CV VARCHAR(10) NOT NULL,
	MA_PB VARCHAR(10) NOT NULL,
	CONSTRAINT PK_NHANVIEN PRIMARY KEY (MA_NV),
	CONSTRAINT FK_NHANVIEN_CONGVIEC FOREIGN KEY (MA_CV)
			REFERENCES CONGVIEC,
	CONSTRAINT FK_NHANVIEN_PHONGBAN FOREIGN KEY (MA_PB)
			REFERENCES PHONGBAN
)
------NHẬP DỮ LIỆU
---BẢNG PHÒNG BAN
DELETE FROM PHONGBAN
INSERT INTO PHONGBAN VALUES ('HC',N'HÀNH CHÍNH',5000000),
							('KT',N'KỸ THUẬT',7000000),
							('KD',N'KINH DOANH',10000000)
	
---BẢNG CONGVIEC
DELETE FROM  CONGVIEC
INSERT INTO  CONGVIEC VALUES ('CV01',N'SỬA CHỮA ĐIỆN NƯỚC',2000000,8000000),	
							 ('CV02',N'DỌN DẸP',1000000,5000000),
							 ('CV03',N'BÁN SẢN PHẨM',8000000,22000000)

---BẢNG NHANVIEN
DELETE FROM NHANVIEN
INSERT INTO NHANVIEN VALUES('NV01',N'TRẦN HOÀNG ANH',5000000,'8/8/1977',N'NAM','CV02','KT'),
							('NV02',N'NGUYỄN HÀ MY',4000000,'10/20/1982',N'NỮ','CV02','HC'),
							('NV03',N'LÊ TUẤN TÚ',6000000,'10/11/1991',N'NAM','CV01','KD')
----TRUY VẤN		
SELECT * FROM PHONGBAN
SELECT * FROM CONGVIEC
SELECT * FROM NHANVIEN

---CÂU 2:
/*2.Hiển thị các nhân viên mà có tuổi từ 30 trở lên bao gồm các thông tin sau: MANV, HOTEN, TENCV, LUONG, NGAYSINH,
TUỔI. (1 điểm) DATEDIFF(YEAR,NGAYSINH,GETDATE()) */
SELECT MA_NV,HOTEN_NV,TEN_CV,LCB,NGAYSINH,YEAR(GETDATE())-YEAR(NGAYSINH) AS TUOI
FROM NHANVIEN JOIN CONGVIEC ON CONGVIEC.MA_CV=NHANVIEN.MA_CV
WHERE YEAR(GETDATE())-YEAR(NGAYSINH) >=30
/*3. Hiển thị các nhân viên có LUONG_MIN từ 950000 đến 1300000 bao gồm các thông tin: MANV, HOTENNV, TENCV,
TENPB, LUONG_MIN. (1 điểm)*/
SELECT MA_NV,HOTEN_NV,TEN_CV,TEN_PB,LUONG_MIN
FROM NHANVIEN  JOIN CONGVIEC ON CONGVIEC.MA_CV=NHANVIEN.MA_CV
			   JOIN PHONGBAN ON PHONGBAN.MA_PB=NHANVIEN.MA_PB
WHERE LUONG_MIN BETWEEN 1000000  AND 9000000
/*4. Hiển thị các thông tin NHANVIEN  họ nguyễn bao gồm các thông tin: MNV, TENNV, TENPB, TENCV. (1 điểm)*/
SELECT MA_NV,HOTEN_NV,TEN_CV ,TEN_PB, LUONG_MIN
FROM NHANVIEN JOIN PHONGBAN ON PHONGBAN.MA_PB=NHANVIEN.MA_PB
			  JOIN CONGVIEC ON CONGVIEC.MA_CV=NHANVIEN.MA_CV
WHERE HOTEN_NV LIKE N'NGUYỄN%'

/*5 Liệt kê các nhân viên có LCB cao nhất gồm các thông tin: MANV, HOTENNV, LCB, TENPB. (1 điểm)*/
SELECT MA_NV,HOTEN_NV,LCB,TEN_PB
FROM NHANVIEN JOIN PHONGBAN ON PHONGBAN.MA_PB=NHANVIEN.MA_PB
ORDER BY LCB DESC	

/*6. Hiển thị thông tin của những phòng ban không có nhân viên nào gồm: MAPB, TENPB. (1 điểm).*/
SELECT MA_PB,TEN_PB FROM PHONGBAN
WHERE NOT EXISTS (SELECT MA_PB,TEN_PB FROM NHANVIEN                     /* SAO LẠI ĐIỀN MA_PB,TEN_PB Ở ĐÂY */
				 WHERE PHONGBAN.MA_PB=NHANVIEN.MA_PB)

/*7. Chèn thêm thông tin vào bảng NHANVIEN (Dữ liệu các cột không được để trống) (1 điểm).*/ /*CHẠY KHÔNG ĐƯỢC*/
INSERT INTO NHANVIEN VALUES 
			('NV04',N'LÊ TUẤN ANH',8000000,'9/12/1991',N'NAM','CV03','KT')


/*8.  Xóa toàn bộ thông tin MACV là CV02. (1 điểm).*/
----XÓA DỮ LIỆU Ở  KHÓA NGOẠI TRƯỚC
DELETE FROM NHANVIEN
WHERE MA_CV='CV02'
---XÓA DỮ LIỆU Ở KHÓA CHÍNH SAU
DELETE FROM CONGVIEC
WHERE MA_CV='CV02'