CREATE DATABASE BUOI3
IF OBJECT_ID('NHANVIEN') IS NOT NULL
DROP TABLE NHANVIEN
GO
CREATE TABLE NHANVIEN
(
	MA_NV VARCHAR(10) NOT NULL,
	HO_TEN NVARCHAR(50) NULL,
	NGAY_SINH DATETIME NULL,
	LUONG MONEY NULL,
	GTINH NVARCHAR(10) NULL,
	CONSTRAINT PK_NHANVIEN PRIMARY KEY(MA_NV)
)
IF OBJECT_ID('DUAN') IS NOT NULL
DROP TABLE DUAN ---DỰ ÁN
GO
CREATE TABLE DUAN
( 
	MA_DA VARCHAR(10) NOT NULL,
	TEN_DA NVARCHAR(50) NULL,
	NAM_BD INT NULL,
	CONSTRAINT PK_DUAN PRIMARY KEY(MA_DA)
)
IF OBJECT_ID('CHAMCONG') IS NOT NULL
DROP TABLE CHAMCONG
GO
CREATE TABLE CHAMCONG
(
	MA_NV VARCHAR(10) NOT NULL,
	MA_DA VARCHAR(10) NOT NULL,
	SO_GIO INT NULL,
	CONSTRAINT PK_CHAMCONG PRIMARY KEY(MA_NV,MA_DA),
	CONSTRAINT FK_NHANVIEN_CHAMCONG FOREIGN KEY(MA_NV) REFERENCES NHANVIEN,
	CONSTRAINT FK_DUAN_CHAMCONG FOREIGN KEY(MA_DA) REFERENCES DUAN
)
-----NHẬP DỮ LIỆU
DELETE FROM NHANVIEN
INSERT INTO NHANVIEN VALUES
					('N01',N'LÊ VĂN TÈO','1/3/2002',19000000,N'NAM'),
					('N02',N'NGỌC NGHÈO','3/3/1988',6000000,N'NAM'),
					('N03',N'ĐẶNG THỊ HIẾU','5/1/1996',60000000,N'NỮ')
DELETE FROM DUAN
INSERT INTO DUAN VALUES
					('D1',N'PHẦN MỀM DẠY ONLINE',2021),
					('D2',N'MẠNG AGENT',2022),
					('D3',N'QUẢN LÝ SÁCH',2020)
DELETE FROM CHAMCONG
INSERT INTO CHAMCONG VALUES
					('N01','D1',220),
					('N03','D1',200),
					('N01','D3',90)
SELECT * FROM NHANVIEN
SELECT * FROM DUAN
SELECT * FROM CHAMCONG

/*Câu 2: Đưa ra thông tin: mã nv, hoten, ngaysinh của những nhân viên có 
lương >7000000 và giới tính là nữ*/
SELECT MA_NV,HO_TEN,NGAY_SINH 
FROM NHANVIEN
WHERE LUONG > 7000000 AND GTINH = N'NỮ'
/*Câu 3: Đưa ra thông tin: MaDA, TenDA của những dự án do nhân viên 
Ngọc Nghèo Tham gia(1đ)*/
SELECT DUAN.MA_DA,TEN_DA 
FROM DUAN JOIN CHAMCONG ON CHAMCONG.MA_DA=DUAN.MA_DA
		 JOIN NHANVIEN ON NHANVIEN.MA_NV=CHAMCONG.MA_NV
WHERE HO_TEN LIKE N'NGỌC TÈO'
/*Câu 4: Đưa ra thông tin nhân viên thông tin hiển thị gồm có: Manv, Hoten, 
tổng so gio của nhân viên có tổng số giờ < 300(1đ)*/
SELECT NHANVIEN.MA_NV,HO_TEN,SUM(SO_GIO) AS TONGGIO
FROM NHANVIEN JOIN CHAMCONG ON CHAMCONG.MA_NV=NHANVIEN.MA_NV
GROUP BY NHANVIEN.MA_NV,HO_TEN 
HAVING SUM(SO_GIO) <300

/*Câu 5: Đưa ra thông tin: manv, hoten, số lượng dự án của mỗi nhân viên(1đ)*/
SELECT NHANVIEN.MA_NV,HO_TEN,count(CHAMCONG.MA_DA) AS SL
FROM NHANVIEN LEFT JOIN CHAMCONG ON CHAMCONG.MA_NV=NHANVIEN.MA_NV
GROUP BY NHANVIEN.MA_NV,HO_TEN 

/*Câu 6: Thêm một bản ghi mới vào bảng nhanvien,dữ liệu phù hợp
( không được nhập giá trị null). (1đ)*/
INSERT INTO NHANVIEN VALUES
					('N04',N'LÊ VĂN NGỘ','2/23/2001',8000000,N'NAM')
/*Câu 7: Thay đổi lại năm bắt đầu của dự án Mạng Agent tăng 2 năm  (1đ)*/
UPDATE DUAN SET NAM_BD = NAM_BD + 2 
WHERE TEN_DA = N'MẠNG AGENT'
/*Câu 8: Xóa dự án đã bắt đầu thực hiện */
ALTER TABLE CHAMCONG
DROP CONSTRAINT FK_DUAN_CHAMCONG

DELETE FROM DUAN 
WHERE NAM_BD < = 2022 

