----TAO CSDL
CREATE DATABASE LAB_8
----BẢNG THUỐC
IF OBJECT_ID('THUOC') IS NOT NULL
  DROP TABLE THUOC
GO
CREATE TABLE THUOC
(
	MATHUOC     VARCHAR(10) NOT NULL,
    TENTH       NVARCHAR(30) NULL,
    DVT         NVARCHAR(10) NULL,
	GIA         MONEY   NULL,
	NHOMDTRI    NVARCHAR(50) NULL,
    CONSTRAINT  PK_THUOC PRIMARY KEY(MATHUOC)
)
-------BẢNG HỒ SƠ
IF OBJECT_ID('HOSO') IS NOT NULL
  DROP TABLE HOSO
GO
CREATE TABLE HOSO
(
	MAHS       VARCHAR(10) NOT NULL,
	HOTEN      NVARCHAR(50) NULL,
	NGSINH     DATETIME NULL,
	GIOITINH   NVARCHAR(10) NULL,
	CMND       NVARCHAR(15) NULL,
	NGAYLAP    DATETIME NULL,
	CONSTRAINT  PK_HOSO PRIMARY KEY(MAHS)
)
-------BANG KHAM BENH
IF OBJECT_ID('KHAMBENH') IS NOT NULL
  DROP TABLE KHAMBENH
GO
CREATE TABLE KHAMBENH
(
	MAKB VARCHAR(10) NOT NULL,
	MAHS VARCHAR(10) NOT NULL,
	NGAYKHAM DATETIME NULL,
	BACSI   NVARCHAR(50) NULL,
	KETLUAN  NVARCHAR(50) NULL,
	CONSTRAINT  PK_KHAMBENH PRIMARY KEY(MAKB),
   CONSTRAINT FK_KHAMBENH_HOSO FOREIGN KEY (MAHS)
	         REFERENCES HOSO
)
------BANG TOA THUOC
IF OBJECT_ID('TOATHUOC') IS NOT NULL
  DROP TABLE TOATHUOC
GO
CREATE TABLE TOATHUOC
(
	MAKB VARCHAR(10) NOT NULL,
	MATHUOC     VARCHAR(10) NOT NULL,
	SOLUONG    INT     NULL,
	CONSTRAINT FK_TOATHUOC_KHAMBENH FOREIGN KEY (MAKB)
                        REFERENCES KHAMBENH,
    CONSTRAINT FK_TOATHUOC_THUOC FOREIGN KEY (MATHUOC)
                        REFERENCES THUOC,
    CONSTRAINT PK_TOATHUOC PRIMARY KEY (MAKB,MATHUOC)
)

---NHAP DU LIEU 
DELETE FROM THUOC
INSERT INTO THUOC VALUES ('T001','astra01',N'Lọ',20000,'covid'),
                         ('T002','penixilin01',N'Chai',30000,'covid'),
	                     ('T003','astra01',N'Lọ',40000,'covid')
	
--NHẬP BẢNG HỒ SƠ
DELETE FROM HOSO
INSERT INTO HOSO VALUES ('HS01',N'Nguyễn Văn A','11/25/2001',N'Nam','034201000','2/22/2022'),
						('HS02',N'Nguyễn Văn B','11/23/1999',N'Nữ','034201000','2/22/2022'),
						('HS03',N'Nguyễn Văn C','11/25/1995',N'Nam','034201000','2/22/2022')
	
--NHẬP BẢNG KHÁM BỆNH
DELETE FROM KHAMBENH
INSERT INTO KHAMBENH VALUES ('KB01','HS01','2/15/2019',N'Hoàng đình Công',N'Không qua khỏi'),
							('KB02','HS02','2/15/2018',N'Hoàng đình Công',N'Không qua khỏi'),
							('KB03','HS01','2/15/2019',N'Nguyễn Minh Quang',N'Không qua khỏi')
	
--NHẬP BẢNG TOA THUỐC
DELETE FROM TOATHUOC
INSERT INTO TOATHUOC VALUES ('KB01','T001',20),
							('KB02','T001',30),
							('KB01','T002',20)
	

SELECT * FROM THUOC
SELECT * FROM HOSO
SELECT * FROM KHAMBENH 
SELECT * FROM TOATHUOC

----CÂU 2:
/*1) Hiển thị (Mathuoc, tenthuoc, soluong) trong những lần 
khám bệnh của hồ sơ có mã là ‘HS01’. */
SELECT THUOC.MATHUOC,TENTH,SOLUONG 
FROM THUOC JOIN TOATHUOC ON TOATHUOC.MATHUOC=THUOC.MATHUOC
		   JOIN KHAMBENH ON KHAMBENH.MAKB=TOATHUOC.MAKB
WHERE MAHS='HS01'
/*2) Hiển thị (Mahs, Hotenbn, Bacsi, Ketluan) được khám bệnh
trong ngày '2/15/2018' */
SELECT HOSO.MAHS,HOTEN,BACSI,KETLUAN 
FROM HOSO JOIN KHAMBENH ON KHAMBENH.MAHS=HOSO.MAHS
WHERE NGAYKHAM = '2/15/2018'
/*3) Hiển thị (Mahs, Hotenbn, Bacsi, Ketluan) được khám bệnh 
trong ngày 1/6/2007. Sxếp d.sách theo Mahs (tăng dần).*/
SELECT HOSO.MAHS,HOTEN,BACSI,KETLUAN 
FROM HOSO JOIN KHAMBENH ON KHAMBENH.MAHS=HOSO.MAHS
WHERE NGAYKHAM = '2/15/2018'
ORDER BY MAHS ASC
/*4)Tìm các loại thuốc thuộc nhóm điều trị “tiêu hoá” 
có giá từ 10000 đến 80000 đồng. */
SELECT * FROM THUOC
WHERE NHOMDTRI= N'covid' and (GIA >= 10000 AND GIA <=80000)
/*5) Hiển thị (Ngkham, Bacsi, Ketluan) của bệnh nhân 
có tên “Nguyen Van A” , s.ngày 11/25/2001 */
SELECT NGAYKHAM,BACSI,KETLUAN 
FROM KHAMBENH JOIN HOSO ON HOSO.MAHS=KHAMBENH.MAHS
WHERE HOTEN = N'Nguyễn Văn A' AND NGSINH= '11/25/2001'
/*6) In chi tiết các lần khám bệnh (Ngkham, Bacsi, Ketluan) 
của bệnh có tên “Nguyen Van A”, sinh ngày 1/7/1970.
Sắp xếp theo Ngkham (tăng dần).*/
SELECT NGAYKHAM,BACSI,KETLUAN 
FROM KHAMBENH JOIN HOSO ON HOSO.MAHS=KHAMBENH.MAHS
WHERE HOTEN=N'Nguyễn Văn A' AND NGSINH = '11/25/2001'
ORDER BY NGAYKHAM ASC




